"""Interactive team composition editor."""

from typing import List, Optional
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.prompt import Prompt, Confirm

from .models.expert import ExpertProposal, ExpertConfig
from .agents.specialist_factory import SpecialistFactory

console = Console()


class TeamEditor:
    """Interactive editor for reviewing and modifying expert team proposals."""

    @staticmethod
    def show_proposed_team(
        proposals: List[ExpertProposal],
        topic: str,
        analysis: str = ""
    ):
        """Display proposed expert team.

        Args:
            proposals: List of expert proposals
            topic: Research topic
            analysis: Optional analysis text from AI
        """
        console.print()
        console.print(Panel.fit(
            f"[bold cyan]Proposed Expert Team[/bold cyan]\n"
            f"Topic: {topic}\n"
            f"Team Size: {len(proposals)} experts",
            border_style="cyan"
        ))

        if analysis:
            console.print(f"\n[bold]Analysis:[/bold] {analysis}\n")

        table = Table(title="Expert Team Composition", show_header=True)
        table.add_column("#", style="dim", width=3)
        table.add_column("Domain", style="cyan")
        table.add_column("Focus Areas", style="green")
        table.add_column("Model", style="yellow")

        for idx, proposal in enumerate(proposals, 1):
            focus = "\n".join(f"• {area}" for area in proposal.focus_areas)
            table.add_row(
                str(idx),
                proposal.expert_domain,
                focus,
                proposal.suggested_model
            )

        console.print(table)
        console.print()

        # Show rationales
        console.print("[bold]Rationale for Each Expert:[/bold]\n")
        for idx, proposal in enumerate(proposals, 1):
            console.print(f"[cyan]{idx}. {proposal.expert_domain}[/cyan]")
            console.print(f"   {proposal.rationale}\n")

    @staticmethod
    def edit_team(
        proposals: List[ExpertProposal],
        topic: str
    ) -> List[ExpertConfig]:
        """Interactive team editing interface.

        Args:
            proposals: Initial expert proposals
            topic: Research topic

        Returns:
            List of finalized ExpertConfig objects
        """
        # Convert proposals to configs
        configs = []
        for idx, proposal in enumerate(proposals):
            expert_id = f"expert_{idx + 1}"
            config = ExpertConfig(
                id=expert_id,
                name=proposal.expert_domain,
                domain=proposal.expert_domain,
                focus_areas=proposal.focus_areas.copy(),
                system_prompt="",  # Will be generated by factory
                provider=proposal.suggested_provider,
                model=proposal.suggested_model
            )
            configs.append(config)

        while True:
            console.print()
            console.print("[bold]Team Editing Menu:[/bold]")
            console.print("  [A] Accept team and continue")
            console.print("  [E] Edit an expert")
            console.print("  [D] Delete an expert")
            console.print("  [N] Add new expert")
            console.print("  [V] View current team")
            console.print("  [Q] Quit (cancel workflow)")
            console.print()

            choice = Prompt.ask(
                "Select action",
                choices=["A", "E", "D", "N", "V", "Q", "a", "e", "d", "n", "v", "q"],
                default="A"
            ).upper()

            if choice == "A":
                # Accept team
                if len(configs) < 2:
                    console.print("[yellow]⚠ Team must have at least 2 experts[/yellow]")
                    continue
                console.print("[green]✓ Team accepted[/green]")
                break

            elif choice == "V":
                # View current team
                TeamEditor._display_current_team(configs)

            elif choice == "E":
                # Edit expert
                if not configs:
                    console.print("[yellow]No experts to edit[/yellow]")
                    continue
                TeamEditor._display_current_team(configs)
                expert_num = Prompt.ask(
                    f"Enter expert number to edit (1-{len(configs)})",
                    default="1"
                )
                try:
                    idx = int(expert_num) - 1
                    if 0 <= idx < len(configs):
                        configs[idx] = TeamEditor._edit_expert(configs[idx])
                    else:
                        console.print("[red]Invalid expert number[/red]")
                except ValueError:
                    console.print("[red]Invalid input[/red]")

            elif choice == "D":
                # Delete expert
                if len(configs) <= 2:
                    console.print("[yellow]⚠ Must have at least 2 experts[/yellow]")
                    continue
                TeamEditor._display_current_team(configs)
                expert_num = Prompt.ask(
                    f"Enter expert number to delete (1-{len(configs)})",
                    default="1"
                )
                try:
                    idx = int(expert_num) - 1
                    if 0 <= idx < len(configs):
                        removed = configs.pop(idx)
                        console.print(f"[green]✓ Removed: {removed.name}[/green]")
                        # Re-index IDs
                        for i, cfg in enumerate(configs):
                            cfg.id = f"expert_{i + 1}"
                    else:
                        console.print("[red]Invalid expert number[/red]")
                except ValueError:
                    console.print("[red]Invalid input[/red]")

            elif choice == "N":
                # Add new expert
                new_config = TeamEditor._create_new_expert(len(configs) + 1)
                if new_config:
                    configs.append(new_config)
                    console.print(f"[green]✓ Added: {new_config.name}[/green]")

            elif choice == "Q":
                # Quit
                if Confirm.ask("[yellow]Cancel workflow?[/yellow]", default=False):
                    console.print("[yellow]Workflow cancelled[/yellow]")
                    return []

        # Generate system prompts for all configs
        for config in configs:
            if not config.system_prompt:
                config.system_prompt = SpecialistFactory._generate_system_prompt(
                    config,
                    topic
                )

        return configs

    @staticmethod
    def _display_current_team(configs: List[ExpertConfig]):
        """Display current team configuration."""
        table = Table(title="Current Team", show_header=True)
        table.add_column("#", style="dim", width=3)
        table.add_column("Domain", style="cyan")
        table.add_column("Focus Areas", style="green", max_width=40)
        table.add_column("Model", style="yellow")

        for idx, config in enumerate(configs, 1):
            focus = ", ".join(config.focus_areas)
            table.add_row(
                str(idx),
                config.domain,
                focus,
                config.model
            )

        console.print(table)

    @staticmethod
    def _edit_expert(config: ExpertConfig) -> ExpertConfig:
        """Edit an individual expert.

        Args:
            config: Expert configuration to edit

        Returns:
            Updated expert configuration
        """
        console.print(f"\n[bold]Editing: {config.name}[/bold]\n")
        console.print(f"Current domain: {config.domain}")
        console.print(f"Current focus areas: {', '.join(config.focus_areas)}")
        console.print(f"Current model: {config.model}")
        console.print()

        # Edit domain
        new_domain = Prompt.ask(
            "Domain (press Enter to keep current)",
            default=config.domain
        )

        # Edit focus areas
        console.print("\n[bold]Focus Areas[/bold] (current):")
        for i, area in enumerate(config.focus_areas, 1):
            console.print(f"  {i}. {area}")

        edit_focus = Confirm.ask("Edit focus areas?", default=False)
        new_focus_areas = config.focus_areas.copy()

        if edit_focus:
            new_focus_areas = []
            console.print("\nEnter new focus areas (one per line, empty line to finish):")
            while True:
                area = Prompt.ask(f"  Focus area {len(new_focus_areas) + 1}", default="")
                if not area:
                    break
                new_focus_areas.append(area)

            if not new_focus_areas:
                new_focus_areas = config.focus_areas  # Keep original if none entered

        # Edit model
        new_model = Prompt.ask(
            "Model",
            choices=["claude-opus-4.5", "claude-sonnet-4.5"],
            default=config.model
        )

        # Create updated config
        return ExpertConfig(
            id=config.id,
            name=new_domain,
            domain=new_domain,
            focus_areas=new_focus_areas,
            system_prompt="",  # Will be regenerated
            provider=config.provider,
            model=new_model
        )

    @staticmethod
    def _create_new_expert(expert_num: int) -> Optional[ExpertConfig]:
        """Create a new expert interactively.

        Args:
            expert_num: Expert number for ID generation

        Returns:
            New ExpertConfig or None if cancelled
        """
        console.print("\n[bold]Add New Expert[/bold]\n")

        domain = Prompt.ask("Expert domain (e.g., 'Game Theory Specialist')")
        if not domain:
            return None

        console.print("\nEnter focus areas (one per line, empty line to finish):")
        focus_areas = []
        while True:
            area = Prompt.ask(f"  Focus area {len(focus_areas) + 1}", default="")
            if not area:
                break
            focus_areas.append(area)

        if not focus_areas:
            console.print("[yellow]⚠ At least one focus area required[/yellow]")
            return None

        model = Prompt.ask(
            "Model",
            choices=["claude-opus-4.5", "claude-sonnet-4.5"],
            default="claude-opus-4.5"
        )

        return ExpertConfig(
            id=f"expert_{expert_num}",
            name=domain,
            domain=domain,
            focus_areas=focus_areas,
            system_prompt="",  # Will be generated
            provider="anthropic",
            model=model
        )
